[versions]
agp = "8.5.0"
coreKtx = "1.13.1"
dotenvKotlin = "6.4.1"
dotenvKotlinVersion = "6.4.1"
githubDotenvKotlin = "6.4.0"
kotlin = "1.9.0"
lifecycleRuntimeKtx = "2.8.4"
orgEclipsePahoAndroidService = "1.1.1"
orgEclipsePahoClientMqttv3 = "1.2.5"
playServicesWearable = "18.2.0"
composeBom = "2024.04.01"
composeMaterial = "1.2.1"
composeFoundation = "1.2.1"
activityCompose = "1.7.2"
coreSplashscreen = "1.0.1"
roomRuntimeVersion = "2.6.1"
tiles = "1.1.0"
tilesMaterial = "1.1.0"
horologistComposeTools = "0.4.8"
horologistTiles = "0.4.8"
watchfaceComplicationsDataSourceKtx = "1.1.1"
lifecycleRuntimeComposeAndroid = "2.8.3"
okhttp = "4.9.3"
appcompat = "1.7.0"
roomCommon = "2.6.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntimeVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
cdimascio-dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenvKotlinVersion" }
dotenv-kotlin = { module = "com.github.cdimascio:dotenv-kotlin", version.ref = "dotenvKotlin" }
dotenv-kotlin-v640 = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "githubDotenvKotlin" }
org-eclipse-paho-android-service = { module = "org.eclipse.paho:org.eclipse.paho.android.service", version.ref = "orgEclipsePahoAndroidService" }
org-eclipse-paho-client-mqttv3 = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "orgEclipsePahoClientMqttv3" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
room-compiler = { module = "androidx.room:room-compiler" }
room-ktx = { module = "androidx.room:room-ktx" }
room-runtime = { module = "androidx.room:room-runtime" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
tiles = { group = "androidx.wear.tiles", name = "tiles", version.ref = "tiles" }
tiles-material = { group = "androidx.wear.tiles", name = "tiles-material", version.ref = "tilesMaterial" }
horologist-compose-tools = { group = "com.google.android.horologist", name = "horologist-compose-tools", version.ref = "horologistComposeTools" }
horologist-tiles = { group = "com.google.android.horologist", name = "horologist-tiles", version.ref = "horologistTiles" }
watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "watchfaceComplicationsDataSourceKtx" }
lifecycle-runtime-compose-android = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "lifecycleRuntimeComposeAndroid" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

